### ISSUE TITLE
Observable.zip problem with multi-threaded worker Verticle

### ISSUE THREAD

**Issue by patrickvankann** [vert-x/mod-rxvertx#20]
I have an issue on Vertx 2.1 using beta4 of RxVertx where a Verticle deployed as a multi-threaded worker Verticle hangs while processing an Observable.zip(). If deployed with multithreaded=false it works fine.

I can reproduce it reliably with this test Verticle:

    package io.vertx.rxvertx;

    import io.vertx.rxcore.java.eventbus.RxEventBus;
    import io.vertx.rxcore.java.eventbus.RxMessage;

    import org.vertx.java.busmods.BusModBase;
    import org.vertx.java.core.json.JsonObject;

    import rx.Observable;
    import rx.functions.Action1;
    import rx.functions.Func2;

    public class MultiThreadedVerticle extends BusModBase {

    @Override
    public void start() {
        super.start();

        final RxEventBus eb = new RxEventBus(vertx.eventBus());
        final String address = getOptionalStringConfig("address",
                "vertx.rxvertx.test");

        eb.<JsonObject> registerHandler(address + ".t1").subscribe(
                new Action1<RxMessage<JsonObject>>() {

                    @Override
                    public void call(final RxMessage<JsonObject> t1) {
                        t1.reply(new JsonObject());
                    }
                });

        eb.<JsonObject> registerHandler(address + ".t2").subscribe(
                new Action1<RxMessage<JsonObject>>() {

                    @Override
                    public void call(final RxMessage<JsonObject> t2) {
                        t2.reply(new JsonObject());
                    }
                });

        eb.<JsonObject> registerHandler(address + ".zip").subscribe(
                new Action1<RxMessage<JsonObject>>() {

                    @Override
                    public void call(final RxMessage<JsonObject> event) {

                        Observable<RxMessage<JsonObject>> t1Send = eb.send(
                                address + ".t1", new JsonObject());

                        Observable<RxMessage<JsonObject>> t2Send = eb.send(
                                address + ".t2", new JsonObject());

                        Observable
                                .zip(t1Send,
                                        t2Send,
                                        new Func2<RxMessage<JsonObject>, RxMessage<JsonObject>, JsonObject>() {

                                            @Override
                                            public JsonObject call(
                                                    RxMessage<JsonObject> t1,
                                                    RxMessage<JsonObject> t2) {
                                                return new JsonObject()
                                                        .putObject("t1",
                                                                t1.body())
                                                        .putObject("t2",
                                                                t2.body());
                                            }
                                        }).subscribe(new Action1<JsonObject>() {

                                    @Override
                                    public void call(JsonObject zipped) {
                                        event.reply(zipped);

                                    }

                                });

                    }

                });
    }

and this integration test.

    package io.vertx.rxvertx;

    import io.vertx.rxcore.java.eventbus.RxEventBus;
    import io.vertx.rxcore.java.eventbus.RxMessage;

    import org.junit.Test;
    import org.vertx.java.core.AsyncResult;
    import org.vertx.java.core.AsyncResultHandler;
    import org.vertx.java.core.json.JsonObject;
    import org.vertx.testtools.TestVerticle;
    import org.vertx.testtools.VertxAssert;

    import rx.functions.Action1;

    public class MultiThreaderWorkerVerticleBugIntegrationTest extends TestVerticle {

    private static final String ADDRESS = "vertx.rxvertx.test";

    @Test
    public void testSendZip() {

        RxEventBus eb = new RxEventBus(vertx.eventBus());

        eb.<JsonObject, JsonObject> send(ADDRESS + ".zip", new JsonObject())
                .subscribe(new Action1<RxMessage<JsonObject>>() {

                    @Override
                    public void call(RxMessage<JsonObject> response) {
                        container.logger().info(response.body());
                        VertxAssert.testComplete();
                    }
                });
    }

    @Override
    public void start() {
        // Set up plumbing
        initialize();

        // Deploy the module
        container.deployWorkerVerticle(MultiThreadedVerticle.class.getName(),
                new JsonObject().putString("address", ADDRESS), 20, true,
                new AsyncResultHandler<String>() {

                    @Override
                    public void handle(AsyncResult<String> asyncResult) {
                        if (asyncResult.succeeded()) {
                            startTests();
                        } else {
                            VertxAssert.fail(asyncResult.cause()
                                    .getLocalizedMessage());
                        }
                    }
                });
    }

    }

This test will freeze - no message is returned.

If you deployWorkerVerticle() with multithreaded false, you will get the zipped response message {"t1":{},"t2":{}}.

**Comment by petermd** [comment]
Cool thx for re-checking.
