### ISSUE TITLE
Implement ability to unregister a handler

### ISSUE THREAD

**Issue by johnoliver** [vert-x/mod-rxvertx#25]
Currently there does not seem to be any mechanism exposed for unregistered a handler created via the RxEventBus

**Comment by rworsnop** [comment]
Would this just be a matter of implementing onUnsubscribed in RxEventBus.ReceiveHandler?

**Comment by petermd** [comment]
Yep - added

**Comment by johnoliver** [comment]
One thing I was not totally clear with this implementation. If multiple observers subscribe to the stream and only one of them unsubscribes, will this implementation remove the subscription from the eventbus? I.e as soon as one observer unsubscribes it will stop all of them?

**Comment by petermd** [comment]
`ReceiveHandler` is a `SingleSubscriptionHandler` which doesn't allow you to register more than one subscriber so I think it's consistent. You'd need to use `publish` or similar if you wanted multiple subscribers.
