### ISSUE TITLE
Rx client support for nio exceptions

### ISSUE THREAD

**Issue by kevlarC** [vert-x/mod-rxvertx#32]
We have recently started using this module with vertx and have come across and issue.
When we are using the rxclient and connect to a down service (connection is just reset) the exception is not propagated to the error handler of the observer chain. 
We are currently using beta5 snapshot and doing the below code to work around the issue

``` java
  rxHttpClient.get(getUri(event), f -> {
                f.exceptionHandler(e -> exceptionHandler(e))));
                f.end();
            })  .flatMap(downloadBody()). ect ...
```

I think that this should not be necessary and the exception should propogate to the onerror handler.

e.g. To get this working in the getNow method

``` java
public Observable<RxHttpClientResponse> getNow(String uri, MultiMap headers) {
    final MemoizeHandler<RxHttpClientResponse,HttpClientResponse> rh=new MemoizeHandler<RxHttpClientResponse,HttpClientResponse>() {
      @Override
      public void handle(HttpClientResponse r) {
        complete(new RxHttpClientResponse(r));
      }
    };
    HttpClientRequest request = core.get(uri, rh);
    request.exceptionHandler(new Handler<Throwable>() {
      @Override
      public void handle(Throwable e) {
        rh.fail(e);
      }
    });
    if ( headers != null ) {
        request.headers().set(headers);
    }

    Observable<RxHttpClientResponse> rxHttpClientResponseObservable = Observable.create(rh.subscribe);
    request.end();
    return rxHttpClientResponseObservable;
  }
```

Thoughts?
Can we patch this in with a integration test and release ?

**Comment by petermd** [comment]
Seems fine, although from the EventBus it has been suggested that we deprecate the hot-observable methods in favour of cold-observable solutions (eg `observeNow()`) that provide a more rx-friendly solution? (eg `getNow()`won't work with `retry()` but `observeNow()` would)

Sound reasonable?

**Comment by KevinJCross** [comment]
Sure ... this seems a bit old now so Ill close this.
