### ISSUE TITLE
How can I keep RxHttpServerRequest object during the whole flows?

### ISSUE THREAD

**Issue by zhangpp520** [vert-x/mod-rxvertx#37]
I'm new to mod-rxvertx,so  maybe I'm asking dumb question.
I just write a server which receives a post request.It's the code:

rxServer
    .http()
    .flatMap(rxRequest -> {
    	//rxRequest.response().setStatusCode(200).end("");
    	return rxRequest.asObservable();
    })
    .map(context -> {return "";})
    .subscribe(new Subscriber<String>(){
        @Override
        public void onNext(String blank) { 
            //I want to use rxRequest here,is it possible????????????
        }
        @Override
        public void onCompleted() { 
            System.out.println("Completed!"); 
        }
        @Override
        public void onError(Throwable e) { 
            System.out.println(e); 
        }
    }); 

I can get the body from the flatMap Operator,but I really want to use RxHttpServerRequest object in the onNext method.How can I do that?

**Comment by petermd** [comment]
do you want the full body & the request? you can nest the body handler inside the request handler eg

```
.flatMap(req -> { 
  return req
    .asObservable()  
    .reduce { o -> .. } // Reduce the request stream to a single string / object
    .map( body -> {
        // you can access body & req here
   }
} 
```
-peter

**Comment by zhangpp520** [comment]
It gives me an 'aha'!
Great help,thank you very much!
