### ISSUE TITLE
Upgrade dependencies and fail method in RxMessage

### ISSUE THREAD

**Issue by mmolimar** [vert-x/mod-rxvertx#44]
Need to upgrade dependencies and to include fail reply method in RxMessage.

I've signed the Eclipse CLA. Submitting pull request #43

**Comment by petermd** [comment]
not showing on https://projects.eclipse.org/user/cla/validate (for the email address in the commit) 

-peter

**Comment by mmolimar** [comment]
The CLA portal doesn't allow me to change my current id which is mmolinabmk (you can try it). Is that ok?

**Comment by petermd** [comment]
i think it has to match on email. can you register another id for this email?

-peter

**Comment by mmolimar** [comment]
This username is assigned by the website. When filling the form it allows you to include your id but afterwards it assigns a different one...
Anyway, the validation also works with my complete email account which is my login at gmail.com.

I hope this helps.

**Comment by petermd** [comment]
so the check i do is to take the email from the commit message and validate that against the Eclipse CLA website. the commit email is mmolina@st..com?

-peter

**Comment by mmolimar** [comment]
Ah ok, could you try it again with that email? Now it works.

**Comment by petermd** [comment]
cool that works - sorry for being pedantic

-peter

**Comment by mmolimar** [comment]
Don't worry. It's all right ;-)

**Comment by petermd** [comment]
#43 accepted, thanks

**Comment by mmolimar** [comment]
Great Peter. BTW, are you going to generate an artifact for Maven Central repo?
